apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-backend-statefulset
  labels:
    app: backend
spec:
  replicas: 1
  serviceName: {{ .Release.Name }}-backend-service
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend 
      labels:
        app: backend
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}-backend
        image: hudsonfranca/videosapp_backend:{{ .Values.tag }}
        resources:
          limits:
            cpu: "0.9"
            memory: "900Mi"
          requests:
            cpu: "0.6"
            memory: "600Mi"
        ports:
        - containerPort: 4000
          name: backend
        env:
          - name: PORT
            value: "{{ .Values.port }}"
          - name: PG_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-database-configmap
                key: db_user
          - name: PG_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-database-configmap
                key: db_host
          - name: PG_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-database-configmap
                key: pg_port
          - name: PG_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-database-configmap
                key: database
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-database-secret
                key: db_password
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-jwt-secret
                key: jwt_key
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-backend-configmap
                key: backendUrl
        volumeMounts:
          - name: {{ .Release.Name }}-backend-pvc 
            mountPath: /usr/src/app/uploads    
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-backend-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: do-block-storage

  


