apiVersion: v1
kind: Service
metadata:
   name: {{ .Release.Name }}-backend-service
   labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 80
      name: backend
      targetPort: 4000
      name: http
      protocol: TCP

  
