jwtKey: c2VjcmV0

database:
  password: c3c1Z2x0ejlvYjJsNWNnNg==
  user: doadmin
  port: 25060
  database: defaultdb
  host: videos-app-database-do-user-9299651-0.b.db.ondigitalocean.com

  
tag: latest

port: 4000

backendUrl: http://videosapp.ml/api

